namespace SvgIconGenerator
{
    /// <summary>
    /// Represents an icon with its SVG metadata and content.
    /// This type is generated by the IconGenerator source generator.
    /// </summary>
    /// <param name="Name">The kebab-case name of the icon (e.g., "circle-user-round").</param>
    /// <param name="DefaultAttributes">The default attributes from the SVG root element (excluding xmlns). Common attributes include: width, height, viewBox, fill, stroke, stroke-width, stroke-linecap, stroke-linejoin.</param>
    /// <param name="InnerContent">The inner HTML content of the SVG element (paths, circles, lines, etc.).</param>
    public sealed record IconDto(string Name, global::System.Collections.Generic.IReadOnlyDictionary<string, string> DefaultAttributes, string InnerContent);
}
